### ISSUE TITLE
$container must not be accessed

### ISSUE THREAD

**Issue by aeq-dev** [mvenghaus/filament-plugin-translatable-inline#1]
Hello,
First of all, thanks a lot for this awesome package which I was waiting for it a longtime :) 
I've installed it and setup translatable trait only in Resource class and remove it from edit & create page,
Bu I'm getting this error when I try to enter other languages values : 
`Typed property Filament\Forms\Components\Component::$container must not be accessed before initialization`

**Comment by mvenghaus** [comment]
Hey,

I think i need a little bit more context. Can you provide some code?

Are you getting the error while typing or when you try to save.

Your resource looks like this?

https://gist.github.com/mvenghaus/5378b99212c44322e08dc333512dbd49

**Comment by aeq-dev** [comment]
When typing,
And it doesn't save

**Comment by mvenghaus** [comment]
@aeq-dev i could reproduce this and released a new version, i hope it will work for you like expected now

**Comment by aeq-dev** [comment]
Hi, 
It works now thanks, but there's a small issue regarding live and afterStateUpdated :/
Check code : 
```
 TranslatableContainer::make(
      TextInput::make('name')
          ->required()
          ->unique(ignoreRecord: true)
          ->label(__('Name'))
          ->live(onBlur: true)
          ->afterStateUpdated(fn(Set $set, ?string $state) => $set('slug', Str::slug($state))),
  ),
  TextInput::make('slug'),
```
Slug doesn't changed.

**Comment by aeq-dev** [comment]
Also if can show error message if we don't set other language values when the field is required :)

**Comment by mvenghaus** [comment]
@aeq-dev 

Since you are no longer on the same state path level and the path is build relative you have these options.

relative:
```php
->afterStateUpdated(fn(Set $set, ?string $state) => $set('../slug', Str::slug($state))),
```

absolute:
```php
->afterStateUpdated(fn(Set $set, ?string $state) => $set('data.slug', Str::slug($state), true)),
```

I will look into the error message issue as soon as possible.

**Comment by mvenghaus** [comment]
@aeq-dev the additional languages are also triggering the field .. i've released a new version 3.0.2 where this is fixed

**Comment by aeq-dev** [comment]
> @aeq-dev
> 
> Since you are no longer on the same state path level and the path is build relative you have these options.
> 
> relative:
> 
> ```
> ->afterStateUpdated(fn(Set $set, ?string $state) => $set('../slug', Str::slug($state))),
> ```
> 
> absolute:
> 
> ```
> ->afterStateUpdated(fn(Set $set, ?string $state) => $set('data.slug', Str::slug($state), true)),
> ```
> 
> I will look into the error message issue as soon as possible.

I tried it but doesn't change the slug :/

**Comment by mvenghaus** [comment]
strange .. i used your example and it works!?

```php
                TranslatableContainer::make(
                    TextInput::make('title')
                        ->required()
                        ->unique(ignoreRecord: true)
                        ->label(__('Name'))
                        ->live(onBlur: true)
                        ->afterStateUpdated(fn(Set $set, ?string $state) => $set('../slug', Str::slug($state))),
                ),
                TextInput::make('slug'),
```

**Comment by aeq-dev** [comment]
Oops ! my bad :D I didn't see the points here ` '../slug'` 
It's my first time to see this strange field code :))) 
Thanks

**Comment by mvenghaus** [comment]
@aeq-dev
Hey,
thanks for your valuable feedback!

I released a new version again, with a big update on validation. Would appreciate your feedback!

**Comment by aeq-dev** [comment]
Thanks for enhancement :)
1. Validation error still doesn't appear 
2. See attached, I cannot hide languages list
![Screenshot from 2024-01-16 23-31-58](https://github.com/mvenghaus/filament-plugin-translatable-inline/assets/81385994/b3d4bf69-8a6f-4419-a3f4-6d39291b8ca6)

**Comment by mvenghaus** [comment]
1. the standard validation, e.g. for required is handled by the browser. So it should look like this
![image](https://github.com/mvenghaus/filament-plugin-translatable-inline/assets/6408081/e23751ec-3733-4ba2-8506-bb1b1f70dbfd)

2. i build this behavior on purpose because without filling these fields you are not able to save.
I added this also to the documention: https://github.com/mvenghaus/filament-plugin-translatable-inline

**Comment by aeq-dev** [comment]
2. I mean I cannot hide the languages inputs again
For validation error, you may just show the languages inputs if it's not open yet

**Comment by mvenghaus** [comment]
you can hide the inputs .. but only if the values are valid
