### ISSUE TITLE
Filament V4 support

### ISSUE THREAD

**Issue by bojmaliev** [mvenghaus/filament-plugin-translatable-inline#16]
that's it.

**Comment by bamod33** [comment]
Any update on this? Since v4 is now release stable

**Comment by mvenghaus** [comment]
I’m on it, I think I’ll do the final touches over the weekend, and the first beta will be released at the beginning of next week.

**Comment by bamod33** [comment]
> I’m on it, I think I’ll do the final touches over the weekend, and the first beta will be released at the beginning of next week.

Hi, any updates on this? Btw, I see there is a [pending PR](https://github.com/mvenghaus/filament-plugin-translatable-inline/pull/18), maybe it helps to finally have compatibility with V4. 

Thanks

**Comment by AlexisSerneels** [comment]
I forked the repo and included Filament 4 Support here: https://github.com/parfaitementweb/filament-plugin-translatable-inline
I'll be maintaining the package.

**Comment by bamod33** [comment]
> I forked the repo and included Filament 4 Support here: https://github.com/parfaitementweb/filament-plugin-translatable-inline I'll be maintaining the package.

Great, thanks!

Btw, do you know why could be this happening?

<img width="368" height="366" alt="Image" src="https://github.com/user-attachments/assets/971762dd-0866-484b-a08e-af3f47ce86ef" />

**Comment by FrazeColder** [comment]
> I forked the repo and included Filament 4 Support here: https://github.com/parfaitementweb/filament-plugin-translatable-inline I'll be maintaining the package.

I am using your package, however, this is what I get:

<img width="1223" height="932" alt="Image" src="https://github.com/user-attachments/assets/ecf8f287-dd18-4305-a65e-6bfbec0e9121" />

Here is my code:
```
class FeatureForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Grid::make()
                    ->schema([
                        Grid::make()
                            ->columnSpan(2)
                            ->columns(1)
                            ->schema([
                                Section::make()
                                    ->columns(1)
                                    ->schema([
                                        TranslatableContainer::make(
                                            TextInput::make('name')
                                                ->maxLength(255)
                                                ->required()
                                        )->requiredLocales(['de', 'en'])
                                    ]),
                            ]),
                        Section::make()
                            ->columnSpan(1)
                            ->columns(1)
                            ->schema([
                                TextEntry::make('id')
                                    ->state(fn($record) => $record->id ?? '---'),
                                TextEntry::make('updated_at')
                                    ->state(fn($record) => isset($record->updated_at) ? $record->updated_at->format('d.m.Y @ H:i:s') : '---'),
                                TextEntry::make('created_at')
                                    ->state(fn($record) => isset($record->created_at) ? $record->created_at->format('d.m.Y @ H:i:s') : '---'),
                            ]),
                    ]),
            ]);
    }
}
```

What am I doing wrong?

**Comment by AlexisSerneels** [comment]
@bamod33 @FrazeColder It's fixed in https://github.com/parfaitementweb/filament-plugin-translatable-inline/releases/tag/4.0.1

**Comment by bamod33** [comment]
> [@bamod33](https://github.com/bamod33) [@FrazeColder](https://github.com/FrazeColder) It's fixed in https://github.com/parfaitementweb/filament-plugin-translatable-inline/releases/tag/4.0.1

It works, thanks!

**Comment by FrazeColder** [comment]
I updated it but I still see the same screen as in the picture above. What am I doing wrong?

```
TranslatableContainer::make(
    TextInput::make('name')
        ->maxLength(255)
        ->required()
)->requiredLocales(['de', 'en'])
```

**Comment by FrazeColder** [comment]
Hey @AlexisSerneels, any update?

I am still facing the issue from above using your package!

<img width="1457" height="489" alt="Image" src="https://github.com/user-attachments/assets/3505cfc8-e891-4076-bd03-7cdb6351f587" />

**Comment by bojmaliev** [comment]
> Hey [@AlexisSerneels](https://github.com/AlexisSerneels), any update?
> 
> I am still facing the issue from above using your package!
> 
> <img alt="Image" width="1457" height="489" src="https://private-user-images.githubusercontent.com/18104426/502845390-3505cfc8-e891-4076-bd03-7cdb6351f587.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjY1OTUzODgsIm5iZiI6MTc2NjU5NTA4OCwicGF0aCI6Ii8xODEwNDQyNi81MDI4NDUzOTAtMzUwNWNmYzgtZTg5MS00MDc2LWJkMDMtN2NkYjYzNTFmNTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjI0VDE2NTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmYTEyNzg2ZWUzYWE0ODk4OTk3YWI0YTc0YWE3NzI2MDc4Mzg0ZjVkNGI2NmM5YzgwOWZkODhjMjBjODkzNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h-A9MsqoPphvbi_8LzHycb-UJH0C6a7M-SLCzuQw5SM">

Any update @AlexisSerneels ?
